BookartBucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: ${self:custom.BookartBucket.name}
    PublicAccessBlockConfiguration:
      BlockPublicAcls: false
      BlockPublicPolicy: false
    OwnershipControls:
      Rules:
        - ObjectOwnership: ObjectWriter

BookartBucketPolicy:
  Type: AWS::S3::BucketPolicy
  Properties:
    Bucket: !Ref BookartBucket
    PolicyDocument:
      Statement:
        - Sid: PublicRead
          Effect: Allow
          Principal: '*'
          Action:
            - s3:GetObject
          Resource: arn:aws:s3:::${self:custom.BookartBucket.name}/*